{{- if .Values.networkpolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "test-app.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "test-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
{{- if .Values.networkpolicy.ingress }}
  ingress:
  {{- toYaml .Values.networkpolicy.ingress | nindent 4 }}
{{- end }}
{{- if .Values.networkpolicy.egress }}
  egress:
  {{- toYaml .Values.networkpolicy.egress | nindent 4 }}
{{- end }}
{{- end }}
