apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
spec:
  podSelector:
    matchLabels:
      {{- include "test-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- if .Values.additional_network_policy.ingress }}
    - from:
      {{- range .Values.additional_network_policy.ingress.namespaces }}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .name | quote }}
      {{- if .ports }}
      ports:
      {{- range .ports }}
        - protocol: TCP
          port: {{ . }}
      {{- end }}
      {{- end }}
      {{- end }}
  {{- else }}
    - {}  # Allow from anywhere
  {{- end }}
  egress:
    # Egress to kube-system namespace for DNS resolution
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
    {{- if .Values.additional_network_policy.egress }}
    # Additional Egress rules
    - to:
      {{- range .Values.additional_network_policy.egress.namespaces }}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .name | quote }}
      {{- if .ports }}
      ports:
      {{- range .ports }}
        - protocol: TCP
          port: {{ . }}
      {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}

---
{{- if .Values.networkpolicy_istio_injection }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy-istio
spec:
  podSelector:
    matchLabels:
      {{- include "test-app.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          istio-injection: enabled  # Select namespace with this label
    - namespaceSelector:
        matchLabels:
          name: istio-system        # Select namespace with deployed Istiod pod
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: istio-system        # Select namespace with deployed Istiod pod
{{- end }}
