# Values to override default

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: demo-app-2.maddevs.org
      paths:
        - path: /
          pathType: Prefix

# Set true if needs networkpolicy for istio service mesh
networkpolicy_istio_injection: true

# Additional rules for network policy
additional_network_policy:
  # Ingress from list of namespaces
  ingress: 
    namespaces:
    - name: monitoring
    - name: ingress-nginx
  # Egress
  egress:
   namespaces:
   - name: "app-1"
     ports: 
     - 8080

pageContent: |
  "<h1>Welcome to Application 2</h1>"
