# Values to override default

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: demo-app-1.maddevs.org
      paths:
        - path: /
          pathType: Prefix

# Set true if needs networkpolicy for istio service mesh
networkpolicy_istio_injection: true

# Additional rules for network policy
additional_network_policy:
  # Ingress from list of namespaces
  ingress:
    namespaces:
    - name: "monitoring"
    - name: "ingress-nginx"
    - name: "app-2"
    - name: "egress-gateway"

pageContent: |
  "<h1>Welcome to Application 1</h1>"

# Istio resources
istio:
  egress_namespace: istio-system
  egress_gateway: istio-egressgateway
  egress_hosts:
  - "maddevs.io"
  - "kubernetes.io"
